name: deploy-gh

on:
  push:
    branches:
      - main

jobs:
  deploy-gh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Use Node.js 19.5"
        uses: actions/setup-node@v3
        with:
          node-version: 19.5
      - name: Deploy
        run: |
          cd github-pages
          git config --global user.email "ludwig.opulski@gmail.com"
          git config --global user.name "Ludwig Opulski"
          npm ci
          npm run deploy
